---
- name: "K8s : stage-e"
  become: true
  hosts:
    - master-b

  tasks:
    - name: "K8s : stage-e : copy join script"
      ansible.builtin.copy:
        src: ./join_masters_cmd.sh
        dest: /tmp/join_masters.sh
        mode: '0755'
    
    - name: "K8s : stage-e : exec join script"
      ansible.builtin.command:
        cmd: /tmp/join_masters.sh
    
    - name: "K8s : stage-e : delete script"
      ansible.builtin.file:
        path: /tmp/join_masters.sh
        state: absent
