---
- name: "K8s : stage-f"
  become: true
  hosts:
    - worker-a
    - worker-b  

  tasks:
    - name: "K8s : stage-f : copy join script"
      ansible.builtin.copy:
        src: ./join_workers_cmd.sh
        dest: /tmp/join_workers.sh
        mode: '0755'
    
    - name: "K8s : stage-f : exec join script"
      ansible.builtin.command:
        cmd: /tmp/join_workers.sh

    - name: "K8s : stage-f : delete script"
      ansible.builtin.file:
        path: /tmp/join_workers.sh
        state: absent
