---
- name: "K8s : stage-d"
  become: true
  hosts:
    - master-a

  vars_files:
    - "../group_vars/common.yml"
    - "../variables/terraform.yml"

  tasks:
    - name: "K8s : stage-d : add kubeadm config dir"
      ansible.builtin.file:
        path: /root/kubeadm
        state: directory
    
    - name: "K8s : stage-d : add kubeadm config"
      ansible.builtin.template:
        src: templates/kubeadm-config.yml.j2
        dest: /root/kubeadm/kubeadm-config.yml

    - name: "K8s : stage-d : init cluster"
      ansible.builtin.command:
        cmd: kubeadm init --config /root/kubeadm/kubeadm-config.yml --upload-certs

    - name: "K8s : stage-d : create .kube dir"
      ansible.builtin.file:
        path: /root/.kube
        state: directory
    
    - name: "K8s : stage-d : copy admin.conf"
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: true
    
    - name: "K8s : stage-d : install flannel"
      ansible.builtin.command:
        cmd: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      environment:
        KUBECONFIG: /root/.kube/config

    # ---
  
    - name: "K8s : stage-d : fetch kubeconfig"
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./admin.conf
        flat: true
      become: true

    - name: "K8s : stage-d : modify kubeconfig"
      ansible.builtin.replace:
        path: ./admin.conf
        regexp: 'server: https://127.0.0.1:6443'
        replace: 'server: https://{{ control_plane_endpoint }}:6443'
      delegate_to: localhost
      become: false

      # ---

    - name: "K8s : stage-d : get cert"
      ansible.builtin.command:
        cmd: kubeadm init phase upload-certs --upload-certs
      register: cert
      changed_when: false

    - name: "K8s : stage-d : extract cert key"
      ansible.builtin.set_fact:
        cert_key: "{{ cert.stdout_lines[-1] }}"

    - name: "K8s : stage-d : generate command for masters"
      ansible.builtin.command:
        cmd: "kubeadm token create --print-join-command --certificate-key {{ cert_key }}"
      register: join_masters_cmd

    - name: "K8s : stage-d : generate command for workers"
      ansible.builtin.command:
        cmd: "kubeadm token create --print-join-command"
      register: join_workers_cmd

    - name: "K8s : stage-d : save command for masters"
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          {{ join_masters_cmd.stdout }}
        dest: ./join_masters_cmd.sh
        mode: '0755'
      delegate_to: localhost
      become: false

    - name: "K8s : stage-d : save command for workers"
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          {{ join_workers_cmd.stdout }}
        dest: ./join_workers_cmd.sh
        mode: '0755'
      delegate_to: localhost
      become: false
